name: CI

on:
  pull_request:
  push:
    branches: [ 'master' ]

env:
  CI: true

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ vars.NODE_VERSION }}
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
